#ifndef INCLUDED_MLISP_OBJECT_BUILTIN_ADD_HH
#define INCLUDED_MLISP_OBJECT_BUILTIN_ADD_HH

#include "MLisp/Object/IBuiltin.hh"

DECLBUILTIN(Add);
DECLBUILTIN(Mul);
DECLBUILTIN(Sub);
DECLBUILTIN(Div);
DECLBUILTIN(Mod);

#endif // INCLUDED_MLISP_OBJECT_BUILTIN_ADD_HH
