#ifndef INCLUDED_MLISP_OBJECT_BUILTIN_ARRAY_HH
#define INCLUDED_MLISP_OBJECT_BUILTIN_ARRAY_HH

#include "MLisp/Object/IBuiltin.hh"

DECLBUILTIN(MakeArray);
DECLBUILTIN(ArrayRef);
DECLBUILTIN(ArraySet);
DECLBUILTIN(ArraySize);

#endif // INCLUDED_MLISP_OBJECT_BUILTIN_ARRAY_HH
