#ifndef INCLUDED_MLISP_OBJECT_BUILTIN_COMPARISON_HH
#define INCLUDED_MLISP_OBJECT_BUILTIN_COMPARISON_HH

#include "MLisp/Object/IBuiltin.hh"

DECLBUILTIN(Eq);
DECLBUILTIN(Lesser);
DECLBUILTIN(LesserEq);
DECLBUILTIN(Greater);
DECLBUILTIN(GreaterEq);

#endif // INCLUDED_MLISP_OBJECT_BUILTIN_COMPARISON_HH
