#ifndef INCLUDED_MLISP_OBJECT_BUILTIN_LIST_HH
#define INCLUDED_MLISP_OBJECT_BUILTIN_LIST_HH

#include "MLisp/Object/IBuiltin.hh"

DECLBUILTIN(Cons);
DECLBUILTIN(Car);
DECLBUILTIN(Cdr);

#endif // INCLUDED_MLISP_OBJECT_BUILTIN_LIST_HH
