#ifndef INCLUDED_MLISP_OBJECT_BUILTIN_MACRO_HH
#define INCLUDED_MLISP_OBJECT_BUILTIN_MACRO_HH

#include "MLisp/Object/IBuiltin.hh"

DECLBUILTIN(Macro);
DECLBUILTIN(MacroLambda);

#endif // INCLUDED_MLISP_OBJECT_BUILTIN_MACRO_HH
