#ifndef INCLUDED_MLISP_OBJECT_BUILTIN_PREDICATE_HH
#define INCLUDED_MLISP_OBJECT_BUILTIN_PREDICATE_HH

#include "MLisp/Object/IBuiltin.hh"

DECLBUILTIN(Null);
DECLBUILTIN(Consp);
DECLBUILTIN(Symbolp);
DECLBUILTIN(Boundp);
DECLBUILTIN(Arrayp);
DECLBUILTIN(Integerp);
DECLBUILTIN(Floatp);

#endif // INCLUDED_MLISP_OBJECT_BUILTIN_PREDICATE_HH
