#ifndef INCLUDED_MLISP_OBJECT_BUILTIN_PRINT_HH
#define INCLUDED_MLISP_OBJECT_BUILTIN_PRINT_HH

#include "MLisp/Object/IBuiltin.hh"

DECLBUILTIN(Print);

#endif // INCLUDED_MLISP_OBJECT_BUILTIN_PRINT_HH
