#ifndef INCLUDED_MLISP_OBJECT_BUILTIN_STREAM_HH
#define INCLUDED_MLISP_OBJECT_BUILTIN_STREAM_HH

#include "MLisp/Object/IBuiltin.hh"

DECLBUILTIN(Open);
DECLBUILTIN(Read);
DECLBUILTIN(GetC);
DECLBUILTIN(Write);

#endif // INCLUDED_MLISP_OBJECT_BUILTIN_STREAM_HH
